// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/WebCraftersGH/Education-service/internal/contracts (interfaces: ProgressSVC)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_ProgressSVC.go -package=mocks . ProgressSVC
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/WebCraftersGH/Education-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProgressSVC is a mock of ProgressSVC interface.
type MockProgressSVC struct {
	ctrl     *gomock.Controller
	recorder *MockProgressSVCMockRecorder
	isgomock struct{}
}

// MockProgressSVCMockRecorder is the mock recorder for MockProgressSVC.
type MockProgressSVCMockRecorder struct {
	mock *MockProgressSVC
}

// NewMockProgressSVC creates a new mock instance.
func NewMockProgressSVC(ctrl *gomock.Controller) *MockProgressSVC {
	mock := &MockProgressSVC{ctrl: ctrl}
	mock.recorder = &MockProgressSVCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressSVC) EXPECT() *MockProgressSVCMockRecorder {
	return m.recorder
}

// ProgressList mocks base method.
func (m *MockProgressSVC) ProgressList(ctx context.Context, userID uuid.UUID, limit, offset int) ([]domain.CheckPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProgressList", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.CheckPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProgressList indicates an expected call of ProgressList.
func (mr *MockProgressSVCMockRecorder) ProgressList(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProgressList", reflect.TypeOf((*MockProgressSVC)(nil).ProgressList), ctx, userID, limit, offset)
}

// SetProgress mocks base method.
func (m *MockProgressSVC) SetProgress(ctx context.Context, userID uuid.UUID, slug string) (domain.CheckPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProgress", ctx, userID, slug)
	ret0, _ := ret[0].(domain.CheckPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetProgress indicates an expected call of SetProgress.
func (mr *MockProgressSVCMockRecorder) SetProgress(ctx, userID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProgress", reflect.TypeOf((*MockProgressSVC)(nil).SetProgress), ctx, userID, slug)
}
