// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/WebCraftersGH/Education-service/internal/contracts (interfaces: ProgressRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_ProgressRepo.go -package=mocks . ProgressRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/WebCraftersGH/Education-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProgressRepo is a mock of ProgressRepo interface.
type MockProgressRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProgressRepoMockRecorder
	isgomock struct{}
}

// MockProgressRepoMockRecorder is the mock recorder for MockProgressRepo.
type MockProgressRepoMockRecorder struct {
	mock *MockProgressRepo
}

// NewMockProgressRepo creates a new mock instance.
func NewMockProgressRepo(ctrl *gomock.Controller) *MockProgressRepo {
	mock := &MockProgressRepo{ctrl: ctrl}
	mock.recorder = &MockProgressRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressRepo) EXPECT() *MockProgressRepoMockRecorder {
	return m.recorder
}

// CreateCheckPoint mocks base method.
func (m *MockProgressRepo) CreateCheckPoint(ctx context.Context, checkPoint domain.CheckPoint) (domain.CheckPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckPoint", ctx, checkPoint)
	ret0, _ := ret[0].(domain.CheckPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckPoint indicates an expected call of CreateCheckPoint.
func (mr *MockProgressRepoMockRecorder) CreateCheckPoint(ctx, checkPoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckPoint", reflect.TypeOf((*MockProgressRepo)(nil).CreateCheckPoint), ctx, checkPoint)
}

// ReadCheckPointByUserID mocks base method.
func (m *MockProgressRepo) ReadCheckPointByUserID(ctx context.Context, userID uuid.UUID, limit, offset int) ([]domain.CheckPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCheckPointByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.CheckPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCheckPointByUserID indicates an expected call of ReadCheckPointByUserID.
func (mr *MockProgressRepoMockRecorder) ReadCheckPointByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCheckPointByUserID", reflect.TypeOf((*MockProgressRepo)(nil).ReadCheckPointByUserID), ctx, userID, limit, offset)
}
